In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [4]:
from sklearn.datasets import make_regression

In [8]:
X,y=make_regression(n_samples=500,n_features=5,coef=False,bias=12,noise=10,random_state=2529)

In [11]:
X,y,w=make_regression(n_samples=500,n_features=5,coef=True,bias=12,noise=10,random_state=2529)

In [12]:
X

array([[ 0.77913208, -1.09701784, -0.14239962,  1.02427891, -1.0708024 ],
       [-0.6925009 ,  0.45535977,  0.34707569, -0.32456746,  0.21970203],
       [-0.03901601, -0.3265115 ,  0.59793721,  0.61686653, -0.6237489 ],
       ...,
       [ 0.33412665,  0.11474505,  0.62425899, -0.09658955, -0.81613498],
       [-1.41673418, -0.96799608, -1.00597234, -0.05460157,  1.20460091],
       [-0.63173072, -0.12198402,  0.59411585,  0.04694857, -1.97796558]])

In [13]:
X.shape,y.shape

((500, 5), (500,))

In [14]:
#w is coef of x
w

array([29.45661718, 60.14529878, 61.7409438 , 13.32437893, 99.08122896])

In [15]:
X[0:5]

array([[ 0.77913208, -1.09701784, -0.14239962,  1.02427891, -1.0708024 ],
       [-0.6925009 ,  0.45535977,  0.34707569, -0.32456746,  0.21970203],
       [-0.03901601, -0.3265115 ,  0.59793721,  0.61686653, -0.6237489 ],
       [-0.61566117, -0.11782129, -0.98234619, -0.78292727,  0.42713048],
       [ 1.30822207, -0.72541559,  0.60187975,  0.33285998,  1.48506184]])

In [16]:
y[0:5]

array([-136.21858395,   49.83118244,  -29.81097858,  -31.74001475,
        193.0687778 ])

In [17]:
from sklearn.model_selection import train_test_split

In [19]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=2529)

In [20]:
#train the model

In [21]:
from sklearn.linear_model import LinearRegression

In [22]:
model=LinearRegression()

In [25]:
model.fit(X_train,y_train)

LinearRegression()

In [26]:
model.intercept_

12.804677404011848

In [27]:
#bias introduced at the time of generating dataset was 12 and predicted intercept is very close to 12. The diff is due to noise=10 introduced at the time of data generation

In [28]:
model.coef_

array([30.14690156, 59.8508539 , 61.00591796, 13.33058614, 98.52732683])

In [29]:
 #predictions

In [30]:
y_pred=model.predict(X_test)

In [31]:
#model evaluation

In [34]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [35]:
mean_squared_error(y_test,y_pred)

93.17298608096334

In [37]:
mean_absolute_error(y_test,y_pred)

7.861503882499261

In [38]:
r2_score(y_test,y_pred)

0.9944221597296871